version: "3.8"
services:
  postfix:
    build: ./postfix
    container_name: postfix
    ports:
      - "2525:25"
    environment:
      - RELAY_HOST=python:1025
    depends_on:
      - python

  python:
    build: ./python
    container_name: python
    ports:
      - "1025:1025"
